spring.application.name=service-one
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
logging.pattern.level=%5p [${spring.application.name:},trace_id=%X{trace_id},span_id=%X{span_id}]
